version: "3.8"

services:
  # MYSQL
  db:
    image: mysql_trainease
    container_name: trainease
    ports:
      - 3306:3306
    volumes:
      - ./mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: trainease
      MYSQL_USER: root
      MYSQL_PASSWORD: p@ssw0rdEASE

#  adminer:
#    image: adminer
#    container_name: database_adminer
#    restart: always
#    ports:
#      - 8080:8080

volumes:
  data: {}
networks:
  default:
    name: trainease_database_default
